### ISSUE TITLE
wiring diagram

### ISSUE THREAD

**Issue by lavericklavericklaverick** [nagimov/adxl345spi#6]
hi, your wiring diagram is wrong, you have the Vin going to Vout on the board, it should go to the top pin on the breakout board

https://github.com/nagimov/adxl345spi/blob/master/adxl345spi_bb.png

**Comment by nagimov** [comment]
You're can power either `VIN` with 5V or `VOUT` with 3.3V.
Breakout board has 3.3V regulator as well as voltage level shifters on both SDA and SCL pullups (see [adafruit schematic](https://learn.adafruit.com/assets/36127)).
3.3V pin is called `VOUT` since it could theoretically be used as 3.3V source if you power the board from 5V and require low current 3.3V somewhere else.
Note that Raspberry Pi GPIO pins are not 5V tolerant, so it's safer to power I2C/SPI devices with 3.3V.

**Comment by lavericklavericklaverick** [comment]
Ah really! Thanks for the information:) sorry for the incorrect issue
